version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ~/docker/volumes/scram2-db:/var/lib/postgresql/data
      # uncomment for initial schema + data
      # TODO: spearate schema from data
      # - docker/init.sql:/docker-entrypoint-initdb.d/01_schema.sql
      # - docker/init.sql:/docker-entrypoint-initdb.d/02_data.sql

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.2
    ports:
      - "10000:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: scram
volumes:
  db_data:
